### ISSUE TITLE
Network Producer/Consumer Confusion

### ISSUE THREAD

**Issue by adrianosorio** [SmartAsphalt159/smart_asphalt#25]
I think their may a confusion with the implementation of the Network Producer/Consumer when I was trying to send data over the network. Usually the producer will create or produce content that others will want to listen too, The consumer will usually just look at its mailbox and see what new information its received. So in this case the consumer would get packets from the vehicles in the fleet and the producer would send out packets we want it too. Currently it seems the producer and consumer do the same thing since they both have get_packet and their is no way to send a packet or group of packets on their own thread. @Akettle44 , currently the workaround is in main to just have it send packets through there.

**Comment by Akettle44** [comment]
The networking consumer isn't used because we are updating the local variable in the producer. The producer listens for packets and updates that variable. The broadcasting has to happen in main because it needs the lastest sensor and control data in order to propagate it (which exists only in main). If we wanted to do that broadcast in a different thread, it would require some sort of synchronization if we would like to explore that, but it adds complexity.
